In [4]:
import numpy as np
#skapa en array av alla integers från x till y exklusive y 
np.arange(10) #x är 0 om bara en integer angivits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(10, 20, 2) #Skapa en array av x till y integers med z hopp på tallinjen

array([10, 12, 14, 16, 18])

In [7]:
np.arange(10, 20, 0.5) #En array of floats!

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [12]:
np.linspace(10,20) #Nu ber vi om hur många steg vi ska ha mellan x, y med z. Om z inte angivits, så 10 steg

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [13]:
np.linspace(10,20,4) #Fyra steg

array([10.        , 13.33333333, 16.66666667, 20.        ])