In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
# Generate dates for the year 2022
dates = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
print(dates)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2022-12-22', '2022-12-23', '2022-12-24', '2022-12-25',
               '2022-12-26', '2022-12-27', '2022-12-28', '2022-12-29',
               '2022-12-30', '2022-12-31'],
              dtype='datetime64[ns]', length=365, freq='D')


In [21]:
# Create column names
prod_columns = [f'productivity work hour {i}' for i in range(1, 9)]
coffee_columns = [f'coffee consumed by hour {i}' for i in range(1, 9)]

['productivity work hour 1', 'productivity work hour 2', 'productivity work hour 3', 'productivity work hour 4', 'productivity work hour 5', 'productivity work hour 6', 'productivity work hour 7', 'productivity work hour 8']


In [18]:
# Generate random values between 80 and 100 to productivity work hour
random_productivity_values = np.random.randint(80, 101, size=(len(dates), 8))

[[96 90 95 ... 87 90 86]
 [94 87 97 ... 86 86 88]
 [81 81 97 ... 84 82 98]
 ...
 [81 86 87 ... 94 94 86]
 [95 95 97 ... 83 91 97]
 [87 88 81 ... 82 90 82]]


In [19]:
# Loop for incremental random values to coffee consumed by hour
for i in range(1, 8):
    random_increment = np.random.randint(0, 4, size=(len(dates),))
    random_coffee_values[:, i] = random_coffee_values[:, i-1] + random_increment

            productivity work hour 1  productivity work hour 2  \
2022-01-01                        96                        90   
2022-01-02                        94                        87   
2022-01-03                        81                        81   
2022-01-04                        97                        96   
2022-01-05                        95                        92   

            productivity work hour 3  productivity work hour 4  \
2022-01-01                        95                        80   
2022-01-02                        97                        99   
2022-01-03                        97                        97   
2022-01-04                        87                        97   
2022-01-05                        88                        95   

            productivity work hour 5  productivity work hour 6  \
2022-01-01                       100                        87   
2022-01-02                        94                        86   
2022-01-

In [ ]:
# Add the columns to the DataFrame
df = pd.DataFrame(random_values_coffee, columns=coffee_columns, index=dates)